# environment.yaml
name: llm-utils
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - google-generativeai>=0.8.3
  - openai>=1.57.4
  - requests>=2.32.3
  - python-dotenv>=1.0.1
  - fastapi>=0.115.6
  - pydantic>=2.10.3
  - pip:
    - wheel